### ISSUE TITLE
✨ raise error if new dependencies are generated (ci/cd)

### ISSUE THREAD

**Issue by juftin** [juftin/hatch-pip-compile#19]
In a CI/CD situation it would be useful to be able to set an environment variable that raises an error if the tooling detects an out of date environment, preventing it from regenerating a lock file without us knowing.

**Comment by oprypin** [comment]
Side comment: an interesting approach here is to just run `pip install` in CI if you already have the lock file 😊
Then you don't bring in any of the heavy machinery - hatch *or* pip-compile, thus taking a lot less time.

But yes, this setting is still definitely important to have and it would fit right in.
