### ISSUE TITLE
Instructions show explicit installation, why not suggest implicit installation?

### ISSUE THREAD

**Issue by oprypin** [juftin/hatch-pip-compile#2]
It's possible to just add this to `pyproject.toml` and it seems to work without manually installing anything other than `hatch`:

```toml
[tool.hatch.env]
requires = [
    "hatch-pip-deepfreeze",
]
```

[**Reference** - seems to have appeared in the docs only since version 1.6?](https://hatch.pypa.io/1.6/plugins/environment/reference/#installation)

I think this should be preferred over the current manual instructions, because it's very inconvenient for people not familiar with any of this stuff (who are just trying to contribute to a project that happens to use hatch):

```bash
pipx inject hatch hatch-pip-compile
```

**Comment by juftin** [comment]
Whoa, I didn't know about `hatch.env.requires`. This sounds like the right way to do this, thank you. I think the `plugin` docs of hatch should mention this as well.
