### ISSUE TITLE
✨ optional hashes?

### ISSUE THREAD

**Issue by juftin** [juftin/hatch-pip-compile#31]
Should the `--generate-hashes` option be optional on the plugin, similar to `pip-compile` or is that desired lockfile behavior by default?

**Comment by juftin** [comment]
See this issue when using hashes on different python versions https://github.com/juftin/hatch-pip-compile/actions/runs/7052973139/job/19199137497

**Comment by oprypin** [comment]
Generating hashes is currently the only default that I always override. It is something to be reserved for people who know that they'll not run into problems with them.

In my guide I always include `pip-compile-hashes = false`
https://oprypin.github.io/mkdocs/user-guide/managing-dependencies/#recommended-config-for-hatch-project-manager

One especially glaring issue with hashes is that git repo - based dependencies are not possible to make a hash of, and so any file that has both hashes and git based dependencies **is impossible to install**.

**Comment by oprypin** [comment]
And something to consider for the future would be.... including the Python version *and* OS into the lock file name :dizzy_face: - I'm sure there will be *some* user who will gladly use this with hashes
Well actually maybe we could already let users do that without too much hassle, by just building more on the context formatting feature for `lock-filename`

**Comment by juftin** [comment]
Yeah agreed - including the OS in the lockfile also clarifies why lockfiles aren't working like they're expected to sometimes

**Comment by oprypin** [comment]
Of course I don't want any of this to be on by default 😅 keep living in a simple world
