### ISSUE TITLE
The choice of paths to lock files

### ISSUE THREAD

**Issue by oprypin** [juftin/hatch-pip-compile#4]
Hi!
Currently this plugin chooses the following path by default: `.hatch/{env_name}.lock`
But I naturally would've chosen this path: `requirements/{env_name}.txt`

This is because:

1. Maybe not necessary to hide it in `.hatch`, because perhaps users who for some reason hate Hatch would just discover the requirements files and use them directly with a sigh of relief.

2. I *think* there are many crawlers of requirements, and they look specifically for `requirements*.txt`. Although I'm not sure which of them allow it to be like `requirements/foo.txt` or if it has to be like `*/requirements-foo.txt`.

   Anyway here are some examples:

   * https://github.com/renovatebot/renovate/blob/0cbd22006f3190974aa099fc37a4128b62d83e55/lib/modules/manager/pip_requirements/index.ts#L9
   * https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems
   * https://thanks.dev/static/ecosystems

Could we think what the path should be, before it's too late to change the default :sweat_smile:

**Comment by juftin** [comment]
I thought about the same thing too, I agree that a `requirements` dir would be a better place. I like `requirements/requirements-{env_name}.txt` or `requirements/{env_name}.txt`

**Comment by oprypin** [comment]
Yeah `requirements/requirements-{env_name}.txt` seems safest, indeed I think most or all of the patterns I mentioned don't recognize `requirements/*.txt`
