### ISSUE TITLE
"PIP_COMPILE_DISABLE" does not affect exit code

### ISSUE THREAD

**Issue by TobyGiacometti** [juftin/hatch-pip-compile#66]
When the environment variable `PIP_COMPILE_DISABLE` is set to `1`, and a lock file update is attempted, the exit code of the affected command is 0. For example: `rm requirements-dev.txt; PIP_COMPILE_DISABLE=1 hatch --env dev run black /path/to/file` exits with the status code 0. This could mask errors in CI/CD environments.

**Comment by juftin** [comment]
Hmmm... I'm not able to replicate this. I'm getting an exit code of 1 due to the raised error: https://github.com/juftin/hatch-pip-compile/blob/46d698dcf943ea6c8d55320c09c12f0283666052/hatch_pip_compile/plugin.py#L139-L142

```shell
rm requirements.txt
PIP_COMPILE_DISABLE=1 hatch --env default run python --version
```

<img width="646" alt="image" src="https://github.com/juftin/hatch-pip-compile/assets/49741340/73c9a215-5bf4-47f4-ba84-8332ee1c8cdc">

Are you able to tell what version of `hatch` / `hatch-pip-compile` you're using? And what OS are you on?

**Comment by juftin** [comment]
Oh... I think I found something here. Is your `dev` environment detached @TobyGiacometti?

I've added a test here for this test case that only fails on an s/ef73cf29a785b535582f92a2666d157712290036) for this test case that only fails on a detached environment: https://github.com/juftin/hatch-pip-compile/pull/67/commits/ef73cf29a785b535582f92a2666d157712290036

**Comment by TobyGiacometti** [comment]
It happens with all environments, whether they are detached or not makes not difference in my case. I am using Hatch 1.9.3 and `hatch-pip-compile` 1.10.0 on Linux. Also tried with `hatch-pip-compile` configuration defaults, same thing.

**Comment by juftin** [comment]
Could you share a `pyproject.toml` / link to the project by chance? I can test inside docker which should hopefully allow me to replicate the issue.

**Comment by juftin** [comment]
🤷 I'm not able to replicate this in docker either, it throws an error with an exit code of 1 as expected again. Can you run the following commands and let me know your output? 

```shell
docker run --rm -it python:3.11 /bin/bash
```

```shell
pip install hatch
mkdir /tmp/hatch-pip-compile-test
cd "$_"
cat <<'EOF' >hatch.toml
[env]
requires = [ "hatch-pip-compile" ]

[envs.default]
type = "pip-compile"
dependencies = [ "pyinfra>=2.9" ]
EOF
PIP_COMPILE_DISABLE=1 hatch -v env run --env default -- python --version
printf "%s\n" "$?"
```

<img width="817" alt="image" src="https://github.com/juftin/hatch-pip-compile/assets/49741340/3f8f4446-df84-481c-bdda-9f53f5968b7f">

**Comment by TobyGiacometti** [comment]
I did some more digging. Turns out that this issue only occurs when using the standalone binaries from https://hatch.pypa.io/latest/install/. Will report this issue upstream.

**Comment by ofek** [comment]
For posterity, this was an error in Hatch: https://github.com/pypa/hatch/pull/1389
