### ISSUE TITLE
How can I use this plugin using hatch config `dirs.env.virtual`?

### ISSUE THREAD

**Issue by jinserk** [juftin/hatch-pip-compile#71]
Hi,

I love to make a "lock" file in my project, but when I use this plugin, I found the config setting `dirs.env.virtual` is not working anymore. Is there way to use `hatch-pip-compile` with `dirs.env.virtual` setting? I need this becase of VScode integration: https://github.com/pypa/hatch/issues/600

**Comment by juftin** [comment]
🤦 I should have put this in the docs. You'll want to set `dirs.env.pip-compile` on your [hatch config file](https://hatch.pypa.io/1.9/config/hatch/#hatch-configuration)

Here's mine:

```toml
[dirs.env]
virtual = ".venv"
pip-compile = ".venv"
```

**Comment by jinserk** [comment]
@juftin You saved my day! Thank you so much!
